name: Send Blog Post to Firestore
on:
  push:
    branches:
      - main
    paths:
      - content/**/*.md
jobs:
  find_blog_posts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.0
      - run: cd .github && pnpm install
      - name: Get changed markdown files
        run: |
          CHANGED=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep ^content/.*.md$ | paste -s -d',')
          echo "Changed_md=$CHANGED" >> $GITHUB_ENV
      - name: Convert markdown and send to Firestore
        uses: ./.github/actions/convertBlogPosts
        with:
          files: "${{ env.Changed_md }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_DZADOK_DEV }}"
